Now leveraging <template> in index.html; updated build script * Now leveraging <template> in index.html that contains a skeleton of the code added to the page by ImageDisplay.  This module now leverages this existing code to speed up (hopefully) the build process for the image.  Performance so far does seem to have increased.  Resolves #6 * With the above, I now feel confident in saying resolves #4 as well.  The placeholder loads in nicely and disappears when it ought to.  Issue #7, though, suggests further enhancements along these tracks that will be implemented in the future. * Renamed output files main.min.js to index.min.js and renamed main.js to index.out.js * Added sorcery to devDependencies.  This package will fix up the source maps that are generated and should hopefully prove useful in future debugging efforts. * As the build process has become more and more convoluted, I took some time to completely revamp the build script.  It is entirely new and now takes optional arguments.  The first specifies what to build (all, server, web, js for both server and web, and css) and the second, if it is the text debug, will skip minification steps (except currently the minifyify step during browserify).  yay * Small formatting changes to the CSS and other stuff too

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,37 +1,122 @@
 #!/bin/sh
 
-# change working directory
-cd "${0%/*}/.."
+# dirs
+BIN_DIR="bin/";
+CSS_DIR="css/";
+JS_DIR="js/";
+SCSS_DIR="scss/";
 
-echo updating submodules...
-git submodule update --remote --recursive
+# files
+_INDEX_NAME="index";
+_INDEX_CSS_DIR="${CSS_DIR}${_INDEX_NAME}";
+_INDEX_JS_DIR="${JS_DIR}${_INDEX_NAME}";
+INDEX_CSS="${_INDEX_CSS_DIR}.css";
+INDEX_CSS_MAP="${INDEX_CSS}.map";
+INDEX_JS="${_INDEX_JS_DIR}.js";
+INDEX_MIN_CSS="${_INDEX_CSS_DIR}.min.css";
+INDEX_MIN_CSS_MAP="${INDEX_MIN_CSS}.map";
+INDEX_MIN_JS="${_INDEX_JS_DIR}.min.js";
+INDEX_MIN_JS_MAP="${_INDEX_NAME}.min.js.map";
+INDEX_OUT_JS="${_INDEX_JS_DIR}.out.js";
+INDEX_OUT_JS_MAP="${INDEX_OUT_JS}.map";
+INDEX_SCSS="${SCSS_DIR}${_INDEX_NAME}.scss";
+SERVER_APP_JS="${JS_DIR}server/image.js";
+TSCONFIG_WEB="tsconfig.web.json";
 
-echo cleaning out js/ directory...
-find ./js/ -maxdepth 9 ! -name ".*" ! -name "js" ! -name "README.md" -delete
+# commands
+BROWSERIFY="${BIN_DIR}browserify";
+POSTCSS="${BIN_DIR}postcss";
+SORCERY="${BIN_DIR}sorcery";
+SCSS="/usr/local/bin/scss";
+TSC="${BIN_DIR}tsc";
+UGLIFYJS="${BIN_DIR}uglifyjs";
 
-echo transpiling web app...
-./bin/tsc -p ./tsconfig.web.json
+checkRegex() {
+	PATTERN=`echo "${2}" | sed "s/ /\$|^/g"`;
+	return $(echo "${1}" | grep -E "^${PATTERN}\$" > /dev/null 2>&1);
+}
 
-echo browserifying web app...
-./bin/browserify ./js/index.js --debug -o ./js/main.js # | ./bin/exorcist ./js/main.js.map > ./js/main.js
+checkTarget() {
+	return $(checkRegex "${TARGET}" "${1}");
+}
 
-# disabling exorcist for now
-#./bin/browserify ./js/index.js --debug | ./bin/exorcist ./js/main.js.map > ./js/main.js
+safeDeleteDir() {
+	find "${1}" -maxdepth 9 ! -name ".*" ! -name $(basename ${1}) ! -name "README.md" -delete;
+}
 
-echo uglifying js...
-./bin/uglifyjs ./js/main.js --compress dead_code,conditionals,comparisons,evaluate,booleans,loops,unused,if_return,reduce_vars,passes=3,keep_fargs=false --mangle --source-map root="https://worst.horse/js",url=main.min.js.map,content=inline --output ./js/main.min.js
+if [ -z "${1}" ]; then
+	TARGET="all";
+else
+	TARGET="$1";
+fi
 
-echo cleaning out css/ directory...
-find ./css/ -maxdepth 9 ! -name ".*" ! -name "css" ! -name "README.md" -delete
+if ! checkTarget "css js server web all"; then
+	echo "usage: build [css | js | server | web | all] [debug]";
+	echo -e "(default to all)\n";
+	echo "cannot build ${TARGET}; exiting";
+	exit 1;
+fi
 
-echo transpiling scss to css...
-find ./scss/ -maxdepth 1 -name "*.scss" -type f -exec sh -c 'scss --style expanded --default-encoding UTF-8 "{}" css/$(basename "{}" ".scss").css' \;
+echo building worst.horse...
 
-echo autoprefixing and minifying css...
-./bin/postcss css/index.css --use autoprefixer --use cssnano | ./bin/exorcist --root / --url /css/index.min.css.map ./css/index.min.css.map > ./css/index.min.css
+echo setting working directory...
+cd "${0%/*}/../";
 
-echo transpiling server app...
-./bin/tsc
+if checkTarget "js server web all"; then
+	echo updating submodules...;
+	git submodule update --remote --recursive;
 
-echo making server app executable...
-chmod +x ./js/server/image.js
+	if checkTarget "js all"; then
+		echo cleaning out js/ directory...;
+		safeDeleteDir "${JS_DIR}";
+	fi
+
+	if [ "${TARGET}" != "server" ]; then
+		echo transpiling web app...;
+		"${TSC}" -p "${TSCONFIG_WEB}";
+
+		echo browserifying web app...;
+		"${BROWSERIFY}" "${INDEX_JS}" --debug | ./bin/exorcist --base "${JS_DIR}" "${INDEX_OUT_JS_MAP}" > "${INDEX_OUT_JS}";
+
+		if [ "${2}" = "debug" ]; then
+			echo not uglifying web app js...;
+			cp "${INDEX_OUT_JS}" "${INDEX_MIN_JS}";
+			cp "${INDEX_OUT_JS_MAP}" "${JS_DIR}${INDEX_MIN_JS_MAP}";
+		else
+			echo uglifying web app js...;
+			"${UGLIFYJS}" "${INDEX_OUT_JS}" --compress --mangle --source-map content="${INDEX_OUT_JS_MAP}",url="${INDEX_MIN_JS_MAP}" --output "${INDEX_MIN_JS}";
+		fi
+
+		echo fixing web app source maps...;
+		"${SORCERY}" -i "${INDEX_MIN_JS}";
+	fi
+fi
+
+if checkTarget "css all"; then
+	echo cleaning out css/ directory...;
+	safeDeleteDir ${CSS_DIR};
+
+	echo transpiling scss to css...;
+	#find "${SCSS_DIR}" -maxdepth 1 -name "*.scss" -type f -exec sh -c 'scss --style expanded --default-encoding UTF-8 "{}" css/$(basename "{}" ".scss").css' \;
+	"${SCSS}" --style expanded --default-encoding UTF-8 "${INDEX_SCSS}" "${INDEX_CSS}";
+
+	if [ "${2}" = "debug" ]; then
+		echo not autoprefixing and minifying css...;
+		cp "${INDEX_CSS}" "${INDEX_MIN_CSS}";
+		cp "${INDEX_CSS_MAP}" "${INDEX_MIN_CSS_MAP}";
+	else
+		echo autoprefixing and minifying css...;
+		"${POSTCSS}" "${INDEX_CSS}" --use autoprefixer --use cssnano | ./bin/exorcist --base "${CSS_DIR}" "${INDEX_MIN_CSS_MAP}" > "${INDEX_MIN_CSS}";
+	fi
+
+	echo fixing css source maps...;
+	"${SORCERY}" -i "${INDEX_MIN_CSS}";
+fi
+
+if checkTarget "js server all"; then
+	echo transpiling server app...;
+	"${TSC}";
+
+	echo making server app executable...;
+	chmod +x "${SERVER_APP_JS}";
+fi
